export enum SECTIONS {
    HOME = 'HOME',
    DEDICATIONS = 'DEDICATIONS',
    GIFS = 'GIFS',
    PLACES = 'PLACES',
    SLIDES = 'SLIDES',
    SUMMARY = 'SUMMARY',
    PEOPLE = 'PEOPLE',
    TICKET = 'TICKET'
}

export interface IDataBase {
    id: number;
    name: string;
    quantity: number;
}

export const DATABASE: IDataBase[] = [
    { "id": 1, "name": "Alex Yañez", "quantity": 4 },
    { "id": 2, "name": "Yazmín Brum", "quantity": 6 },
    { "id": 3, "name": "Noel", "quantity": 7 },
    { "id": 4, "name": "Chema", "quantity": 3 },
    { "id": 5, "name": "Fernando", "quantity": 5 },
    { "id": 6, "name": "Raquel Lopez", "quantity": 3 },
    { "id": 7, "name": "Victor Martínez", "quantity": 2 },
    { "id": 8, "name": "Yuly Cruz", "quantity": 1 },
    { "id": 9, "name": "Claudia Sánchez", "quantity": 2 },
    { "id": 10, "name": "Laurea Verdooren", "quantity": 2 },
    { "id": 11, "name": "Carlos Rangel", "quantity": 2 },
    { "id": 12, "name": "Botello", "quantity": 4 },
    { "id": 13, "name": "Alfredo Méndez", "quantity": 6 },
    { "id": 14, "name": "Marco Nejapa", "quantity": 2 },
    { "id": 15, "name": "Julian Luna", "quantity": 2 },
    { "id": 16, "name": "Ricardo Alvarez", "quantity": 4 },
    { "id": 17, "name": "Molina", "quantity": 1 },
    { "id": 18, "name": "Tello", "quantity": 2 },
    { "id": 19, "name": "Mary", "quantity": 5 },
    { "id": 20, "name": "Adriana Rico", "quantity": 3 },
    { "id": 21, "name": "Adriana Santamaría", "quantity": 3 },
    { "id": 22, "name": "Jose Castro", "quantity": 1 },
    { "id": 23, "name": "Monserrat Contreras", "quantity": 2 },
    { "id": 24, "name": "Enrique Rios", "quantity": 4 },
    { "id": 25, "name": "Laura Ortega", "quantity": 2 },
    { "id": 26, "name": "Liliana Glz", "quantity": 2 },
    { "id": 27, "name": "Aaron Mtz", "quantity": 2 },
    { "id": 28, "name": "Victor Ortega", "quantity": 2 },
    { "id": 29, "name": "Fidel Aldana", "quantity": 1 },
    { "id": 30, "name": "Alfredo", "quantity": 2 },
    { "id": 31, "name": "Monse", "quantity": 3 },
    { "id": 32, "name": "Caro", "quantity": 1 },
    { "id": 33, "name": "Azucena", "quantity": 2 },
    { "id": 34, "name": "Oli", "quantity": 4 },
    { "id": 35, "name": "Lulu", "quantity": 3 },
    { "id": 36, "name": "Javier", "quantity": 2 },
    { "id": 37, "name": "Margarita", "quantity": 2 },
    { "id": 38, "name": "Olvera", "quantity": 4 },
    { "id": 39, "name": "Fausto Espinosa", "quantity": 2 },
    { "id": 40, "name": "Mónica Chávez", "quantity": 1 },
    { "id": 41, "name": "Angy Lopez", "quantity": 1 },
    { "id": 42, "name": "Leticia Flores", "quantity": 2 },
    { "id": 43, "name": "Liliana", "quantity": 2 },
    { "id": 44, "name": "Tere", "quantity": 4 },
    { "id": 45, "name": "Martín", "quantity": 2 },
    { "id": 46, "name": "Valentina", "quantity": 3 },
    { "id": 47, "name": "Mauricio", "quantity": 3 },
    { "id": 48, "name": "Karen", "quantity": 3 },
    { "id": 49, "name": "Seomara", "quantity": 3 },
    { "id": 50, "name": "Nahomi", "quantity": 3 },
    { "id": 51, "name": "Rubí", "quantity": 3 },
    { "id": 52, "name": "Esteban", "quantity": 3 },
    { "id": 53, "name": "Ayram", "quantity": 3 },
    { "id": 54, "name": "Melany", "quantity": 3 },
    { "id": 55, "name": "Prof. Onofre", "quantity": 3 },
    { "id": 56, "name": "Prof. Vilchis", "quantity": 3 },
    { "id": 57, "name": "Andrea", "quantity": 3 },
    { "id": 58, "name": "Santiago", "quantity": 3 },
    { "id": 59, "name": "Yamilet", "quantity": 3 },
    { "id": 60, "name": "Jonathan", "quantity": 3 },
    { "id": 61, "name": "Sarahi", "quantity": 3 },
    { "id": 62, "name": "Michelle", "quantity": 3 },
    { "id": 62, "name": "Valeria", "quantity": 3 },
    { "id": 62, "name": "Oliver", "quantity": 3 },
    { "id": 62, "name": "Sandra", "quantity": 3 },
    { "id": 62, "name": "Elihu", "quantity": 3 },
    { "id": 62, "name": "Ivan", "quantity": 3 },
    { "id": 62, "name": "Edward", "quantity": 3 },
    { "id": 62, "name": "Alan", "quantity": 3 },
    { "id": 62, "name": "Melanie", "quantity": 3 },
    { "id": 62, "name": "Prof. Araceli Guzmán", "quantity": 3 }
]

